// This file is automatically generated: DO NOT MODIFY!

foreign class EngineClass {
    construct new () {}

    foreign GetTime()
    foreign SetEngine(arg0)
}

foreign class TimeModule {
    foreign GetDeltatime()
}

var Engine = EngineClass.new()

