groups:
  - name: devs # name of the group
    reviewers: 1 # how many reviewers do you want to assign?
    usernames: # github usernames of the reviewers
      - santiberna
      - MuskettaMan
      - mmzala
      - LeoHellmig
      - luuk234
      - lyvanettinger
      - dumitrurares14
      - LarsJanssen21
      - VengarvdWal