#version 460
#include "particle_binds.glsl"

layout (set = 2, binding = 0) buffer CulledInstancesSSB
{
    CulledInstances culledInstances;
};

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    particleCounters.aliveCount = particleCounters.aliveCountAfterSimulation;
    particleCounters.aliveCountAfterSimulation = 0;
    culledInstances.count = 0;
    particleCounters.deadCount = max(0, particleCounters.deadCount);
}