cd ..
set DEFAULT="--preset x64-Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=OFF -DUSE_UNITY_BUILD=OFF -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_PCH="--preset x64-Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=ON -DUSE_UNITY_BUILD=OFF -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_UNITY="--preset x64-Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=OFF -DUSE_UNITY_BUILD=ON -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_UNITY_PCH="--preset x64-Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=ON -DUSE_UNITY_BUILD=ON -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"

::python scripts/python/profile_build_times.py -b "build/x64-Release" -f "--target VulkanMemoryAllocator" -c %WITH_UNITY%
python scripts/python/profile_build_times.py -b "build/x64-Release" -c %DEFAULT% %WITH_PCH% %WITH_UNITY% %WITH_UNITY_PCH%
pause