cd ..
set DEFAULT="--preset CI-CD -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=OFF -DUSE_UNITY_BUILD=OFF -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_PCH="--preset CI-CD -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=ON -DUSE_UNITY_BUILD=OFF -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_UNITY="--preset CI-CD -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=OFF -DUSE_UNITY_BUILD=ON -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"
set WITH_UNITY_PCH="--preset CI-CD -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_PCH=ON -DUSE_UNITY_BUILD=ON -DWARNINGS_AS_ERRORS=OFF -DCOMPILE_SHADERS=OFF"

python scripts/python/profile_build_times.py -b "build/CI-CD" -c %DEFAULT% %WITH_PCH% %WITH_UNITY% %WITH_UNITY_PCH%
pause