name: Build

on:
  pull_request

jobs:

  build-project:
    name: Build Project

    strategy:
      matrix:
        platform: [windows-latest] #, ubuntu-latest]
        configuration: [Debug] #, RelWithDebInfo, Release]

    runs-on: ${{ matrix.platform }}

    steps:

    #   - name: Install LLVM and Clang
    #     uses: KyleMayes/install-llvm-action@v2
    #     with:
    #       version: "18.1.8"

      - name: Checkout Project
        uses: actions/checkout@v4.1.7


      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
        with:
          build_dir: build/${{ matrix.platform }}/${{ matrix.configuration }}
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          