name: PR-Checks

on:
  pull_request

jobs:

  build-project:
    name: Build Project

    strategy:
      fail-fast:
        true
      matrix:
        platform: [windows-latest] #, ubuntu-latest]
        configuration: [Debug] #, RelWithDebInfo, Release]

    runs-on: ${{ matrix.platform }}

    env:
        PRESET_PREFIX: ${{ matrix.platform == 'windows-latest' && 'x64' || matrix.platform == 'ubuntu-latest' && 'WSL' }} 
        PRESET_SUFFIX: ${{ matrix.configuration == 'Debug' && 'Debug' || matrix.configuration == 'Release' && 'Release' || 'RelWithDebInfo' }} 

    steps:

      - name: Install Ninja
        # uses: ashutoshvarma/setup-ninja@master
        run: ${{ matrix.platform == 'windows-latest' && 'choco install ninja -y' || 'sudo apt-get install ninja-build' }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.0
        with:
            vulkan-query-version: 'latest'

      - name: Check Dependencies
        run: clang --version && ninja --version && cmake --version

      - name: Checkout Project
        uses: actions/checkout@v4.1.7
        with:
            submodules: 'true'

      - name: Configure Project
        run: cmake --preset ${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }} -DWARNINGS_AS_ERRORS=ON
          