name: PR-Checks

on:
  pull_request

jobs:

  build-project:
    name: Build Project

    strategy:
      fail-fast:
        true
      matrix:
        platform: [ubuntu-latest] #, ubuntu-latest]
        configuration: [Debug] #, RelWithDebInfo, Release]

    runs-on: ${{ matrix.platform }}

    env:
        PRESET_PREFIX: ${{ matrix.platform == 'windows-latest' && 'x64' || matrix.platform == 'ubuntu-latest' && 'WSL' }} 
        PRESET_SUFFIX: ${{ matrix.configuration == 'Debug' && 'Debug' || matrix.configuration == 'Release' && 'Release' || 'RelWithDebInfo' }} 

    steps:

    #   - name: Update Package Manager
    #     run: sudo apt update && sudo apt install ninja-build build-essential libncurses5 libc++-dev -y

      - name: Install Ninja
        run: sudo apt install ninja-build

    #   - name: Install LLVM and Clang
    #     uses: egor-tensin/setup-clang@v1
    #     with:
    #         version: latest
    #         platform: x64

    #   - name: Set up GCC
    #     uses: egor-tensin/setup-gcc@v1
    #     with:
    #         version: latest
    #         platform: x64

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
            version: latest
            cache: true

      - name: Check Dependencies
        run: clang --version && ninja --version && cmake --version

      - name: Checkout Project
        uses: actions/checkout@v4.1.7
        with:
            submodules: 'true'

      - name: Check Current Dir
        run: ls

      

      - name: Build and Configure Project
        run: cmake --preset ${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }} -DWARNINGS_AS_ERRORS=ON && cmake --build build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}
          