name: PR-Checks

on:
  pull_request

jobs:

  build-project:
    name: Build and Test Project

    strategy:
      fail-fast:
        true
      matrix:
        platform: [ubuntu-latest] #, ubuntu-latest]
        configuration: [Debug, RelWithDebInfo, Release]

    runs-on: ${{ matrix.platform }}

    env:
        PRESET_PREFIX: ${{ matrix.platform == 'windows-latest' && 'x64' || matrix.platform == 'ubuntu-latest' && 'WSL' }} 
        PRESET_SUFFIX: ${{ matrix.configuration == 'Debug' && 'Debug' || matrix.configuration == 'Release' && 'Release' || 'RelWithDebInfo' }} 

    steps:

      - name: Install Ninja
        run: sudo apt install ninja-build tree

      - name: Install Dependencies
        run: sudo apt-get install libvulkan-dev libsdl2-dev -y

      - name: Check Tools
        run: clang --version && ninja --version && cmake --version

      - name: Checkout Project
        uses: actions/checkout@v4.1.7
        with:
            submodules: 'true'

      - name: Configure Project
        run: cmake --preset ${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }} -DWARNINGS_AS_ERRORS=ON

      - name: Build Project
        run: cmake --build build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}

      - name: Test Project
        run: build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}/Engine -T
          