name: PR-Checks

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build and Test Project

    strategy:
      fail-fast: true
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
        configuration: [ Debug, Release ]

    runs-on: ${{ matrix.platform }}

    env:
      EXTRA_ARGS: -DWARNINGS_AS_ERRORS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ 
      PRESET_PREFIX: ${{ matrix.platform == 'windows-latest' && 'x64' || matrix.platform == 'ubuntu-latest' && 'WSL' }}
      PRESET_SUFFIX: ${{ matrix.configuration }}

    steps:
      # Check out project

      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          lfs: 'true'

      # Install all dependencies

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true
          
      # Configure, Build and Test

      - name: Configure Project
        run: cmake --preset ${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }} ${{ env.EXTRA_ARGS }}

      - name: Build Project
        run: cmake --build build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}

      - name: Test Project
        run: build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}/Engine -T
          